version: '3.9'

services:
  postgresdb:
    image: postgres:15
    env_file:
      - ./.env
    container_name: courier-pg
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
    ports:
      - "5432:5432"
    volumes:
      - "courier-vol:/var/lib/postgres"

  courier:
    depends_on:
      - postgresdb
    links:
      - postgresdb
    build:
      context: .
    container_name: courier-dev
    restart: always
    env_file:
      - ./.env
    environment:
      DB_HOST: postgresdb
      DB_PORT: $DB_PORT
      DB_TYPE: $DB_TYPE
      DB: $DB
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - ./:/courier-app
    ports:
      - "4000:4000"
volumes:
  courier-vol: